### ISSUE TITLE
Page: Access bibentries (single or multiple) should be within the browser, not by downloading files.

### ISSUE THREAD

**Issue by potthast** [ir-anthology/ir-anthology#15]

**Comment by najtin** [comment]
If we get the bibtex directly from the dblp servers, then we can not display the file instead of downloading it. 


There are a few options here:

- write a javascript page, that downloads and displays the file as if the file is shown directly
- reverse proxy the request and change the header on the fly
- crawl and host the dblp bib tex entries ourselfs (would advice against that, as it creates more problems than it solves)

**Comment by potthast** [comment]
I'm not sure: The "Copy to clipboard" button does download the Bibtex file directly from DBLP, no? Then it should be easy to, instead of copying the downloaded file to clipboard, display it on the web page.
